version: '3.9'

services:
  nestapp:
    container_name: nestapp
    image: ibrahim/nestapp:1.0.0
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DB_TYPE=postgres
      - PG_HOST=db
      - PG_USER=postgres
      - PG_PASSWORD=flysql
      - PG_DB=nestdb
      - PG_PORT=5432
      - JWT_SECRET=why
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=flysql
      - POSTGRES_DB=nestdb
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}